fixed-validation-create-survey
RadyaBen/Survey_App pull request #6
Opened 2021-06-29 07:50 UTC by RadyaBen

2021-06-29 08:21 UTC, arlek777 requested changes

2021-06-29 08:21 UTC, arlek777 commented on src/containers/CreateSurvey/CreateSurvey.js
> +		let { survey } = this.state;
You can remove it and handle it in the same way as the survey title field. You just need to add a name to your checkbox input. So you will have only 1 handle user input handler and that's it.

2021-06-29 08:21 UTC, arlek777 commented on src/containers/CreateSurvey/CreateSurvey.js
> +			} else if ( questionError.length > 0 || questionTypeError.length > 0) {
This check does NOTHING, remove it, I don't know why  you need this if it just does nothing.

2021-06-29 08:21 UTC, arlek777 commented on src/containers/CreateSurvey/CreateSurvey.js
> +			if (!questionError) {
Please, don't forget to check the same with !questionError && !questionTypeError, because you can't add new question without question and questionType

2021-06-29 08:21 UTC, arlek777 commented on src/containers/CreateSurvey/CreateSurvey.js
> +			} else {
Again, piece of useless code, remove it and don't leave such code in future, if it does not do anything.

2021-06-29 08:21 UTC, arlek777 commented on src/containers/CreateSurvey/CreateSurvey.js
> +			} else if (title.length > 6 && question.length > 10 && questionType.length > 7) {
You already check on title length in titleCheckHandler, here you just need "else" without checks at all. 
So if(titleError.lenght > 0 || questionArr.length === 0) it means you have errors or you don't have questions. If you have them and no titleError, then you can add survey.

So here you have if/else and that's it.

2021-06-29 08:23 UTC, arlek777 requested changes

2021-06-29 08:23 UTC, arlek777 commented on src/containers/CreateSurvey/CreateSurvey.js
> +			.filter((field) => field.question.length > 9)
Why do you filter for question.length > 9? Is it possible to have such objects in your array? As I remember you have validation to prevent even adding such elements to an array so I don't understand why you need it. Be careful with it.

2021-06-29 18:22 UTC, RadyaBen commented on src/containers/CreateSurvey/CreateSurvey.js
> +			.filter((field) => field.question.length > 9)
![image](https://user-images.githubusercontent.com/49837519/123847504-53519080-d91f-11eb-8a25-20088a960f02.png)

I think that without this check my code won't work correctly, as it shown in the screenshot.

2021-06-29 18:33 UTC, RadyaBen commented on src/containers/CreateSurvey/CreateSurvey.js
> +			} else if (title.length > 6 && question.length > 10 && questionType.length > 7) {
![image](https://user-images.githubusercontent.com/49837519/123848709-b09a1180-d920-11eb-966a-b1c84c841ec5.png)
![image](https://user-images.githubusercontent.com/49837519/123848757-bc85d380-d920-11eb-9af2-aa7539ee0016.png)

If the question and questionType fields are empty, and the title field is filled, then by clicking, first, the Add Question button, and then Create Survey, the code continues to execute. And at the end, a new poll will be created as shown in the screenshot. But with this check everything works correctly.

2021-06-29 19:05 UTC, RadyaBen commented on src/containers/CreateSurvey/CreateSurvey.js
> +			if (!questionError) {
Ok, thanks)

2021-06-29 19:05 UTC, RadyaBen commented on src/containers/CreateSurvey/CreateSurvey.js
> +			} else if ( questionError.length > 0 || questionTypeError.length > 0) {
Ok

2021-06-30 15:47 UTC, arlek777 approved these changes

2021-06-30 15:47 UTC, merged